### ISSUE TITLE
Setup a Next13 project

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#1]
setup project with eslint, prettier and pre-commit hook

**Comment by arpit01923** [comment]
Hey @bhtibrewal , I want to take this task

**Comment by mohammadkhizerkhan** [comment]
Hi @bhtibrewal , i want to work on this.
please assign it to me.

**Comment by mohammadkhizerkhan** [comment]
@bhtibrewal ETA will be 16/july/2023
