### ISSUE TITLE
Write a Unit Test for "BackButton"

### ISSUE THREAD

**Issue by sunilk429** [Real-Dev-Squad/skill-tree-frontend#124]
### Issue Description
The `BackButton` component needs unit tests to verify its core functionality

### Expected Behavior
The `BackButton` component should have unit tests to ensure:
- It correctly navigates back using the `next/navigation` router when no route is specified.
- It pushes the specified route when the `route` prop is provided.
- It renders the correct label, defaulting to "Back" if no label is passed.
- The `ArrowLeft` icon is rendered alongside the label.

### Current Behavior
There are currently no unit tests for the `BackButton` component.

### Reproducibility
- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce
1. Navigate to the project's test directory.
2. Look for any existing test files related to the `BackButton` component.
3. Confirm that no test file currently exists for this component.

### Severity/Priority
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Information
The following core test cases should be implemented:

- **Default Behavior**: Verify that clicking the `BackButton` calls the `back()` method when no `route` prop is provided.
- **Route Navigation**: Test that the `push()` method is called with the correct `route` when the `route` prop is specified.
- **Label Rendering**: Ensure that the correct label is displayed, defaulting to "Back" if no label is provided.
- **Icon Rendering (ArrowLeft)**: Verify that the `ArrowLeft` icon is rendered next to the label.

### Checklist
- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to resolving this issue.

**Comment by yesyash** [comment]
- closing this as the required changes are done in #136
