### ISSUE TITLE
Write a Unit Test for "InputErrorMessage" component

### ISSUE THREAD

**Issue by sunilk429** [Real-Dev-Squad/skill-tree-frontend#125]
### Issue Description

The `InputErrorMessage` component has not unit tests to verify its intended behavior, when a error occurs it should display a  message as a fallback.
### Expected Behavior

The `InputErrorMessage` component should have unit tests that cover the following key functionalities:
- Proper rendering of the error message when the `show` prop is `true`.
- The error message should not be rendered when the `show` prop is `false`.
- The component should display the correct error message text passed through the `message` prop.

### Current Behavior

There are no unit tests currently implemented for the `InputErrorMessage` component.

### Reproducibility
- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce

1. Navigate to the test directory in the project.
2. Search for any test file related to the `InputErrorMessage` component.
3. Observe that no test file exists.

### Severity/Priority
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

**Comment by yesyash** [comment]
- closing this as the required changes are done in #144
