### ISSUE TITLE
Write a Unit Test for "PageError" component

### ISSUE THREAD

**Issue by sunilk429** [Real-Dev-Squad/skill-tree-frontend#127]
### Issue Description
The `PageError` component needs essential unit tests to verify its core functionality, including rendering, button interactions, and the reload behavior.

### Expected Behavior
- The `PageError` component should render correctly with a message indicating "Something went wrong!".
- The "Reload page" button should be visible and trigger a page reload when clicked.

### Current Behavior
There are no existing unit tests for the `PageError` component.

### Reproducibility
- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce
1. Navigate to the project directory containing the `PageError` component.
2. Check if there are unit tests related to this component.
3. Observe that no unit tests exist.

### Severity/Priority
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Information
Implement the following test cases:
1. Ensure that the "Something went wrong!" message is displayed.
2. Verify that the `Button` with the reload icon is rendered.
3. Ensure the `Button` triggers a page reload when clicked.

### Checklist
- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the required changes are done in #145
