### ISSUE TITLE
Endorsement From UI

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#17]
Figma: https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=649-1028&mode=design&t=511nPvYRgRXmabYj-4

**Comment by BhavikaTibrewal** [comment]
### Requirements
create UI components with dummy data
write tests for the components
Make the components reusable

### Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150
