### ISSUE TITLE
[FE] integrate GET endorsements API with UI

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#26]
### Requirements
- integrate GET endorsements API call with pagination
- write tests for the same

Things that can be done to improve performance
- the API response should be cached such that page=1 once fetched revisiting that page we get the data from our cache

Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150

**Comment by yesyash** [comment]
- issue no longer valid as the changes are already merged to develop
