### ISSUE TITLE
[FE]implement filter on the Endorsement board UI

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#27]
Dropdown to selected user and skill and then filter endorsement based on it 
also filter based on endorsement status - APPROVED/ PENDING/ REJECTED

Figma: https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=23-895&mode=design&t=4pFn6Bo7XxeFyIJK-0
Design and Implementation Discussion should be documented before starting work on the task

### Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150

**Comment by yesyash** [comment]
- issue no longer valid as we're not implementing this currently
