### ISSUE TITLE
[FE]create endorsement

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#28]
### Requirements
- make the endorsement form functional 
- integrate `/users?user` API - present in RDS BE
- integrate `/skills/{name}` - skill tree API 
and make the API call to create endorsement

Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150

**Comment by yesyash** [comment]
- issue no longer valid the changes for this is already merged to develop
