### ISSUE TITLE
[FE]Authentication and Authorisation

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#29]
## Authentication and Authorisation
Design doc link - https://docs.google.com/document/d/1oFSvj_6ijdzASVa5QdGcMLxlHQnkpXa_anzI82qKcwk/edit#heading=h.b1fnfb7zo1h5
- [x] #39
- [ ] Frontend Auth with node backend.
- [ ] Frontend Auth with skill tree backend. 
- [ ] Retry mechanism in frontend.

**Comment by yesyash** [comment]
- closing this as it is taken care of in #80
