### ISSUE TITLE
Frontend setups

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/skill-tree-frontend#34]
### Description

- [x] Setup Readme 
- [x] Setup staging environment
- [ ] Setup prod environment

**Comment by satyam73** [comment]
# Setup for staging
**Branch** - `develop`
**Build command** - `yarn build:staging`

# Setup for production
**Branch** - `main`
**Build command** - `yarn build:production`

**Comment by prakashchoudhary07** [comment]
I was not able to find the staging build command in the repo (yarn build:staging) do we need to create one?

**Comment by satyam73** [comment]
> taging build command in the repo (yarn build:staging) do we need to

Yes the PR for this is merged now please check

**Comment by satyam73** [comment]
Steps for Skill tree frontend poduction deployment - https://github.com/Real-Dev-Squad/skill-tree-frontend/issues/38

**Comment by satyam73** [comment]
Staging Link - http://staging-skilltree.realdevsquad.com

**Comment by satyam73** [comment]
Closing this since this task got completed.
Others issues for this task
- #38 
- #67 

Deployed links for staging and production,

Staging - https://staging-skilltree.realdevsquad.com/
Production - https://skills.realdevsquad.com/
