### ISSUE TITLE
Add search functionality for endorsements

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#46]
### Issue Description
More details to be filled

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as this is not in the development pipeline
