### ISSUE TITLE
create the UI for the Request Board screen

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#5]
### Design
https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=23-895&mode=design&t=4pFn6Bo7XxeFyIJK-0

### Requirements
- create UI components with dummy data 
- write tests for the components
- Make the components reusable

### Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150

**Comment by manish591** [comment]
Please assign me. ETA will be 17th August.
1 Day - Test
2 Day - Task
1 Day - Review
