### ISSUE TITLE
create UI for the endorsement details slide over

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/skill-tree-frontend#6]
### Design
https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=201-2316&mode=design&t=4pFn6Bo7XxeFyIJK-0

### Requirements
create UI components with dummy data
write tests for the components
Make the components reusable

### Additional Info
Ask your doubts at https://discord.com/channels/673083527624916993/1114589148901294150

**Comment by suhaasya** [comment]
@bhtibrewal Can you please assign this task to me?
ETA will be 21/08/2023
