### ISSUE TITLE
Update yarn lock file as per latest yarn version and add next static export configuration in next config file

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#66]
### Issue Description
We have to update the yarn lock file as per the latest yarn version present in our package.json to avoid any dependency versions conflicts, and also update the next.config.js for static export.

### Expected Behavior
yarn lock file should be updated and next config file should be updated so as to export the static build.

### Current Behavior
yarn lock file is not updated and configs are not set in next config file.

### Screenshots
n/a

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as we have switching to npm
