### ISSUE TITLE
Change env variables for same build command across different environments

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#69]
### Issue Description
We have to change env variables for same build command across different environments.

### Expected Behavior
One build command can be used in any environment and we can use environment variable to check what environment the build has to be generated for.

### Current Behavior
Currently we have different build command and env files for different environments, like:
`yarn build:production` for production
`yarn build:staging` for staging

### Screenshots
n/a

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
n/a

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the changes for this are done in #78
