### ISSUE TITLE
Add query hook with react query for self user details

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#70]
### Issue Description
Add query hook with react query for self user details

### Expected Behavior
Add query hook with react query for self user details

### Current Behavior
Add query hook with react query for self user details

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the changes are already done in #80
