### ISSUE TITLE
Remove fetch from hooks

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#71]
### Issue Description
Right now we're using fetch at some places but we should use axios instead of fetch.

### Expected Behavior
It should use axios instead of fetch.

### Current Behavior
It is using fetch at some places.

### Screenshots
n/a

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by Hansraj8149** [comment]
Hey, I wanted to start my open-source contribution journey and was looking for some issues to contribute on, happy to work on this issue. If you may assign this to me.😊😊

**Comment by satyam73** [comment]
> Hey, I wanted to start my open-source contribution journey and was looking for some issues to contribute on, happy to work on this issue. If you may assign this to me.😊😊

Nice you can take it up

**Comment by yesyash** [comment]
- closing this as it is no longer valid
