### ISSUE TITLE
[FE] Integrate Update Endorsement Status (Super User Only) with UI

### ISSUE THREAD

**Issue by Atifsid** [Real-Dev-Squad/skill-tree-frontend#73]
### Requirements
- Integrate Update Endorsement Status API
- write tests for the same

### Additional Information
**Design Doc** - [Here](https://docs.google.com/document/d/1ysN2GxN3aONqf7st1xnkmrOeY-9HXjP99Yfq1t9lkTk/edit?usp=sharing)
**Backend Issue** - [Here](https://github.com/Real-Dev-Squad/skill-tree-backend/issues/45)

**Comment by yesyash** [comment]
- closing this as it is no longer valid
