### ISSUE TITLE
FEAT: Create add endorsements page with API integrations

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/skill-tree-frontend#76]
### Overview
We have to create a page where users can create endorsements for others as well as themselves. We can create an endorsement for users by selecting their username and skill with a description.

### User Story
- [ ]  As a user I can create endorsement of myself or for others.
- [ ]  As a user I can search the "user" for creating endorsement with a dropdown type search component.
- [ ]  As a user I can select the skill from the dropdown type search component while creating an endorsement.
- [ ]  As a user I can create skills if not found from the dropdown type search component and then create the endorsement.
- [ ]  As a user I should be able to add description to my endorsement for additional details about the endorsements I am creating.

### Requirements
- Follow TDD for the feature.

### Reference(Images, Design, Links etc.)

>Note: Design will be slightly updated

Figma link - https://www.figma.com/file/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?type=design&node-id=951-80&mode=design&t=w7utit7YDK44Cotx-0

### Acceptance Criteria

- [ ] User can create endorsement of theirself or for others.
- [ ] User can search the user for creating endorsements with a dropdown type search component.
- [ ] User can select the skill from dropdown type search component.
- [ ] User can create skill if not found from dropdown type search component.
- [ ] User should be able to fill description while creating endorsement.

### Scope
- [ ] User can create endorsement of theirself or for others.
- [ ] User can search the user for creating endorsements with a dropdown type search component.
- [ ] User can select the skill from dropdown type search component.
- [ ] User can create skill if not found from dropdown type search component.
- [ ] User should be able to fill description while creating endorsement.

### Note
- As of now we're only making for adding upvote/downvote(removing will be done later*)
- Do not add this to so that user can create this endorsement and skills.
- Built with the set of skills as of now instead of creating a skill(like user can create React/ReactJS, which will be handling in separate issue).
- Add validations for inputs

**Comment by bhtibrewal** [comment]
User can add upvote or down vote while creating endorsement (To Be discussed)

**Comment by ankushdharkar** [comment]
> User can add upvote or down vote while creating endorsement (To Be discussed)

Good clarification. The person creating the endorsement should automatically be counted as upvote, since they created it for the purpose of endorsing that skill for the user.

**Comment by yesyash** [comment]
- closing this as it is no longer valid because the add endorsements page API design has changed and we're not supporting up vote / down vote
