### ISSUE TITLE
create a list of components and utils we want to unit test

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/skill-tree-frontend#81]
### requirements
- create a list of components we would want to unit test and create individual tickets for each component.

**Comment by sunilk429** [comment]
I would like to pick this issue

**Comment by yesyash** [comment]
- [design doc](https://docs.google.com/document/d/1774uRJOAiAAWbeFH505fbDQN8R05-Z96DbJ9e2zAlF4/edit?usp=sharing)
