### ISSUE TITLE
Create a Endorsement form in the super admin dashboard.

### ISSUE THREAD

**Issue by Abhay5855** [Real-Dev-Squad/skill-tree-frontend#91]
### Issue Description
Create a endorsement form in the super admin dashboard that consist of 3 fields - 
- A combo box component that allows you to choose a skill and also search from the list and select.
- user for whom endorsement is being created.
- description.

### Expected Behavior
A form should be displayed in the dashboard that displays 3 form fields - 
- A combo box component that allows you to choose a skill / search for particular skill from the list.
- user for whom endorsement is being created.
- description.
After completely filling the details should be able to submit the endorsement.

### Current Behavior
Currently there is no endorsement form present in the Dashboard.

### Screenshots
![image](https://github.com/Real-Dev-Squad/skill-tree-frontend/assets/71277980/79c0eff0-72c3-4b83-a897-74c5a34657f7)

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Additional Information
- Basic design for the form - https://www.figma.com/design/NoGWCSYI5qF1CGmwn0XKQH/skill-tree?node-id=727-313&t=22skwU2JfjmlFBPG-0
- The form should be keyboard accessible.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by yesyash** [comment]
- closing this as the changes have been merged
